// backend/compiler.mjs
// The Job Card Compiler: NL job description -> validated manifest -> OpenClaw skill file.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { validateManifest } from "../contracts/manifestSchema.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const seatsDir = join(here, "..", "contracts", "seats");

// STEP 1 (MOCK): parse NL -> manifest.
// In the starter we load the pre-written manifest for the seat.
// >>> TODO (real): call the edge SLM / LLM with the NL job text and the
//     ManifestSchema as the output contract, then validate the JSON it returns.
export async function parseJobToManifest(seatId) {
  const raw = await readFile(join(seatsDir, `${seatId}.json`), "utf8");
  return JSON.parse(raw);
}

// STEP 2: validate against the contract (this is the guardrail gate).
// STEP 3: emit an OpenClaw skill file (SOUL.md-style) with hard blocks.
export async function compile(seatId) {
  const manifest = validateManifest(await parseJobToManifest(seatId));
  const job = await readFile(join(seatsDir, `${seatId}.job.txt`), "utf8").catch(() => "");
  const skill = emitSkill(manifest, job);
  const outDir = join(here, "..", "build", "skills");
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, `${seatId}.md`), skill, "utf8");
  return { manifest, skill };
}

// Used by the frontend's "write the job in Italian" box. 
// Real NL->manifest parsing is still a TODO — this still loads the pre-written
// manifest for the seat, but emits the skill doc from the TEXT THE USER TYPED,
// so the box is genuinely wired to something instead of a no-op textarea.
// >>> TODO (real): replace with an edge-SLM/LLM call: jobText -> manifest JSON,
//     validated by ManifestSchema, same as parseJobToManifest does today.
export async function compileWithJobText(seatId, jobText) {
  const manifest = validateManifest(await parseJobToManifest(seatId));
  const skill = emitSkill(manifest, jobText || "");
  const outDir = join(here, "..", "build", "skills");
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, `${seatId}.md`), skill, "utf8");
  return { manifest, skill, usedCustomJobText: Boolean(jobText) };
}

export function emitSkill(m, job) {
  const block = (arr) => arr.map((x) => `- ${x}`).join("\n");
  return `# SOUL — ${m.seat}
> Generated by the Job Card Compiler. Do not edit by hand; edit the job description and recompile.

## Mission (from the job description)
${job.trim() || "(job description not provided)"}

## Runtime binding
- location: ${m.location}
- model: edge=${m.model.edge}, fallback=${m.model.fallback}
- memory: read=[${m.memory.read}] write=[${m.memory.write}]${m.memory.partition ? ` partition=${m.memory.partition}` : ""}

## Allowed tools
${block(m.tools)}
${m.skills.length ? `\n## Skills (per client)\n${block(m.skills)}` : ""}

## HARD BLOCKS (enforced at runtime, not prompt hints)
${block(m.refuses)}
${m.gate ? `\n## Human gate\n- ${m.gate}` : ""}

## Proof / metering
- artifact: ${m.artifact || "(none)"}
- unit: ${JSON.stringify(m.unit)}
`;
}
